### PR TITLE
Support ppc64le

### PR DESCRIPTION
**Pull request by leofang**
This is needed by CuPy (conda-forge/cupy-feedstock#134).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@conda-forge-admin, please restart ci

**Comment by leofang** [comment]
@hmaarrfk This is ready, PTAL 🙂

**Comment by hmaarrfk** [comment]
can you add support for aarch as well?

**Comment by hmaarrfk** [comment]
also, I've run benchmarks and i don't feel like this is actually any day than cpython anymore

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
@hmaarrfk Could you help restart the failed Travis test due to connection error? Drone CI is looping over the variants one by one and I don't wanna restart the whole thing...

**Comment by leofang** [comment]
> also, I've run benchmarks and i don't feel like this is actually any day than cpython anymore

Thanks, glad to know. Is this true for all supported Python versions (3.6+)? I assume we still need it for pypy?

**Comment by hmaarrfk** [comment]
Thanks for that. I know drone is slow. I have started using azure more liberally at times.

I kinda don't want to change defaults unless we *need* to. Since this package builds relatively quickly, and is not chagning too much , i think we can continue to use drone for now. thanks for this.

**Comment by leofang** [comment]
Yup no problem @hmaarrfk. Thanks for kicking off the CI. Drone is good for now. No need to cross compile.

**Pull request merged**
